name: Deploy Laravel para public_html via FTP

on:
  push:
    branches:
    - main
    - staging # Adicione outras branches conforme necessário

jobs:
  test:
    name: Executar Testes
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Obter código mais recente
      uses: actions/checkout@v3

    - name: Cache do Composer
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-

    - name: 📦 Instalar dependências do Composer
      run: composer install --prefer-dist --no-interaction --no-scripts

    - name: 🛠️ Configurar ambiente de teste
      run: cp .env.example .env && php artisan key:generate

    - name: 🧪 Rodar testes
      run: ./vendor/bin/phpunit

  deploy:
    name: Deploy Laravel via FTP
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: 📥 Obter código mais recente
      uses: actions/checkout@v3

    - name: Cache do NPM
      uses: actions/cache@v3
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-

    - name: 📦 Instalar dependências do NPM
      run: npm install

    - name: Verificar mudanças no frontend
      id: check-frontend
      run: |
        if git diff --name-only HEAD~1 | grep -E 'resources/|vite.config.js|webpack.mix.js|package.json|yarn.lock|package-lock.json'; then
          echo "build_needed=true" >> $GITHUB_ENV
        else
          echo "build_needed=false" >> $GITHUB_ENV
        fi

    - name: 🔨 Compilar assets do frontend (Vite ou Laravel Mix)
      if: env.build_needed == 'true'
      run: |
        if [ -f "vite.config.js" ]; then
          npm run build
        elif [ -f "webpack.mix.js" ]; then
          npm run prod
        fi

    - name: 📂 Enviar arquivos via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home2/startt33/public_html/
        local-dir: ./
        exclude: |
          **/.git*
          **/.env*
          **/node_modules/*
          **/vendor/*

    - name: Executar pós-deploy no servidor
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home2/startt33/public_html/
        local-dir: ./
        exclude: |
          **/*  # Exclui tudo
          !deploy.sh  # Apenas envia deploy.sh
