name: Deploy Laravel App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, ctype, fileinfo, openssl, pdo, mysql, tokenizer, xml
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader

    - name: Install Node dependencies
      run: npm ci

    - name: Build assets
      run: npm run prod

    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ssh.starttofinish.com.br
        username: startt33@starttofinish.com.br
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/your-project
          git pull origin main
          composer install --no-dev --prefer-dist --optimize-autoloader
          npm ci
          npm run prod
          php artisan optimize
