name: Deploy Laravel App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, ctype, fileinfo, openssl, PDO, mysql, pgsql, sqlite, tokenizer, xml
        tools: composer:v2

    - name: Install dependencies
      run: |
        composer install --no-dev --prefer-dist --optimize-autoloader

    # Opcional: Se usa npm (para assets)
    - name: Install Node dependencies
      run: |
        npm ci
      working-directory: /path/to/your/assets # se aplic치vel

    - name: Build assets
      run: |
        npm run prod
      working-directory: /path/to/your/assets # se aplic치vel

    - name: Setup environment
      run: |
        cp .env.example .env
        php artisan key:generate
      env:
        APP_ENV: production
        # Adicione outras vari치veis de ambiente necess치rias aqui

    - name: Run migrations
      run: php artisan migrate --force

    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ssh.starttofinish.com.br
        username: startt33@starttofinish.com.br
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/your/project/on/server
          git pull origin main
          composer install --no-dev --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          # Se usar Horizon/Queues:
          php artisan horizon:terminate
          # Se usar Octane:
          php artisan octane:reload
