name: Deploy Laravel App to Hostgator

on:
  push:
    branches:
      - main  # Altere para o branch que você deseja fazer deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Install dependencies
      run: |
        sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USER }}@${{ secrets.FTP_SERVER }} "cd public_html/ && composer install --no-dev --optimize-autoloader"

    - name: Run migrations
      run: |
        sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USER }}@${{ secrets.FTP_SERVER }} "cd public_html/ && php artisan migrate --force"

    - name: Deploy application
      run: |
        sshpass -p "${{ secrets.FTP_PASSWORD }}" rsync -avz --exclude='.env' --exclude='.git' --exclude='node_modules' --exclude='storage' ./ ${{ secrets.FTP_USER }}@${{ secrets.FTP_SERVER }}:public_html/
        sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USER }}@${{ secrets.FTP_SERVER }} "cd public_html/ && php artisan config:cache && php artisan route:cache && php artisan view:cache"

    - name: Restart services (if needed)
      run: |
        sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USER }}@${{ secrets.FTP_SERVER }} "sudo service php-fpm restart"